name: daily-cron
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1' # At 06:00 every monday

env:
  LISTEN_BRAINZ_TOKEN: ${{ secrets.LISTEN_BRAINZ_TOKEN }}
  DEEZER_ACCESS_TOKEN: ${{ secrets.DEEZER_ACCESS_TOKEN }}
  DEEZER_PLAYLIST_NAME: ${{ secrets.DEEZER_PLAYLIST_NAME }}

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run prod